### ISSUE TITLE
mysql error - compose version 2.0

### ISSUE THREAD

**Issue by mjstealey** [mjstealey/wordpress-nginx-docker#4]
@behinam - migrating your issue to it's own issue thread (will remove from other thread that is reserved for internal documentation)

---

Hello
when i run i get this error:

```
wordpress | MySQL Connection Error: (2002) Connection refused
wordpress |
wordpress | Warning: mysqli::__construct(): (HY000/2002): Connection refused in Standard input code on line 22
```

my yml file

```
`version: '2'
services:
nginx:
image: nginx:latest
container_name: nginx
ports:
- '80:80'
- '443:443'
volumes:
- ./nginx:/etc/nginx/conf.d
- ./logs/nginx:/var/log/nginx
- ./wordpress:/var/www/html
- ./certs:/etc/letsencrypt
- ./certs-data:/data/letsencrypt
links:
- wordpress
restart: always

mysql:
image: mariadb
container_name: mysql
ports:
- '3306:3306'
volumes:
- ./mysql:/var/lib/mysql
environment:
- MYSQL_ROOT_PASSWORD=123456789
restart: always

wordpress:
image: wordpress:php7.2-fpm
container_name: wordpress
volumes:
- ./wordpress:/var/www/html
environment:
- WORDPRESS_DB_NAME=wordpress
- WORDPRESS_TABLE_PREFIX=wp_
- WORDPRESS_DB_HOST=mysql
- WORDPRESS_DB_USER=uwp
- WORDPRESS_DB_PASSWORD=123456
links:
- mysql
restart: always`
```

**Comment by mjstealey** [comment]
@behinam - Your error is due to the mysql container not having the `uwp` user defined. You'll need to initialize the mysql container with the proper user as well as the database that the `uwp` user should own for your Wordpress installation. Settings options for the `mysql` container can be found here: [https://hub.docker.com/_/mariadb/](https://hub.docker.com/_/mariadb/)

Example docker-compose file:

```yaml
version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./wordpress:/var/www/html
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
    links:
      - wordpress
    restart: always

  mysql:
    image: mariadb
    container_name: mysql
    ports:
    - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_USER=uwp             # set user to be same as $WORDPRESS_DB_USER
      - MYSQL_PASSWORD=987654321   # set password to be same as $WORDPRESS_DB_PASSWORD
      - MYSQL_DATABASE=wordpress   # set database to be same as $WORDPRESS_DB_NAME
    restart: always

  wordpress:
    image: wordpress:php7.2-fpm
    container_name: wordpress
    volumes:
      - ./wordpress:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=uwp
      - WORDPRESS_DB_PASSWORD=987654321
    links:
      - mysql
    restart: always
```

You can also bring the database up first, and then the rest of the containers afterwards to minimize the connection errors while the mysql container is standing up and configuring itself.

```console
$ docker-compose up -d mysql
Creating mysql ... done
```

Watch the mysql logs for it to finish

```console
$ docker-compose logs mysql
Attaching to mysql
mysql        | Initializing database
mysql        |
mysql        |
mysql        | PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
mysql        | To do so, start the server, then issue the following commands:
mysql        |
mysql        | '/usr/bin/mysqladmin' -u root password 'new-password'
mysql        | '/usr/bin/mysqladmin' -u root -h  password 'new-password'
...
mysql        | 2018-08-22 18:03:52 0 [Note] Added new Master_info '' to hash table
mysql        | 2018-08-22 18:03:52 0 [Note] mysqld: ready for connections.
mysql        | Version: '10.3.9-MariaDB-1:10.3.9+maria~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
```

And then bring the rest of the stack up

```console
$ docker-compose up -d
mysql is up-to-date
Creating wordpress ... done
Creating nginx     ... done
```

You'll then find your running site ready to be configured at the URL that you deployed to:

<img width="1114" alt="screen shot 2018-08-22 at 2 08 10 pm" src="https://user-images.githubusercontent.com/5332509/44481874-fa146f00-a614-11e8-9972-fa2e5c1937ef.png">
